### PR TITLE
Add instructions to share the model cache

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by joelgrus** [comment]
does that work? are you sure that the cache exists locally?

**Comment by schmmd** [comment]
Uhg--good point.  See my changes @joelgrus.

**Comment by joelgrus** [comment]
sorry, that wasn't exactly my question. this is going to spin up on some random k8s machine; why would you ever expect that machine to have this cache populated? if the app crashes and restarts won't it likely start up somewhere else?

**Comment by schmmd** [comment]
The docker command is in a readme for users to run locally.

**Comment by joelgrus** [comment]
Got it, 👍

**Pull request merged**
